# Generated by Django 3.2.8 on 2021-11-27 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MainCat',
            fields=[
                ('mcid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('addressline1', models.CharField(max_length=20)),
                ('addressline2', models.CharField(max_length=20)),
                ('addressline3', models.CharField(max_length=20)),
                ('pin', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SubCat',
            fields=[
                ('scid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('basePrice', models.IntegerField()),
                ('discount', models.IntegerField(blank=True, default=0, null=True)),
                ('finalPrice', models.IntegerField(blank=True, default=0, null=True)),
                ('color', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('specification', models.TextField()),
                ('stock', models.BooleanField(default=True)),
                ('pic1', models.ImageField(upload_to='images/')),
                ('pic2', models.ImageField(upload_to='images/')),
                ('pic3', models.ImageField(upload_to='images/')),
                ('pic4', models.ImageField(upload_to='images/')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.brand')),
                ('mainCat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.maincat')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.seller')),
                ('subCat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.subcat')),
            ],
        ),
    ]
