# Generated by Django 3.2.8 on 2021-12-05 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20211204_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('addressline1', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('addressline2', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('addressline3', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('pin', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('city', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('state', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('pic', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='specification',
        ),
        migrations.AddField(
            model_name='product',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
