# Generated by Django 3.2.8 on 2021-12-25 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='mode',
            field=models.CharField(default='COD', max_length=10),
        ),
    ]
