# Generated by Django 3.2.8 on 2021-12-26 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_checkout_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('cuid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
    ]
