# Generated by Django 3.2.8 on 2021-12-26 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscibe',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
