# Generated by Django 3.2.8 on 2021-12-26 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_subscibe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscibe',
            new_name='Subscribe',
        ),
    ]
