# Generated by Django 3.2.8 on 2022-01-02 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_rename_subscibe_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='otp',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='otp',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
